/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: false
    inverse1: true
    inverse2: true
    # Back Lidar
    laser1Alpha: 0.0
    laser1AngleMax: 20.0
    laser1AngleMin: -110.0
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: -0.85
    laser1YOff: 0.34
    laser1ZOff: 0.0
    # Front Lidar
    laser2Alpha: 180.0
    laser2AngleMax: 20.0
    laser2AngleMin: -110.0
    laser2B: 0
    laser2G: 255
    laser2R: 0
    laser2XOff: 0.91
    laser2YOff: -0.25
    laser2ZOff: 0.0
    pointCloudTopic: cloud_in
    pointCloutFrameId: laser
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /lidar_1/scan
    scanTopic2: /lidar_2/scan
    show1: true
    show2: true
    use_sim_time: true

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00174144853
    #angle_increment: 0.0005
    angle_min: -3.1415927410125732
    angle_max: 3.1415927410125732
    inf_epsilon: 1.0
    max_height: 1.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_min: 0.15000000596046448
    range_max: 40.0
    scan_time: 0.049273036420345306
    target_frame: laser
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: true
    time_increment: 2.7389125534682535e-05