controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    position_controllers:
      type: position_controllers/JointGroupPositionController

velocity_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - base_rear_left_wheel_joint
      - base_rear_right_wheel_joint

    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - effort


position_controllers:
  ros__parameters:
    use_sim_time: true
    joints:
      - base_front_left_sterring_joint
      - base_front_right_sterring_joint
    command_interface: 
      - position
    state_interface: 
      - position
      - effort

